# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

flutter_application_path = './../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'FlutterTabsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  install_all_flutter_pods(flutter_application_path)
  
  pod 'Masonry'

  use_frameworks!

  # Pods for FlutterTabsDemo

end
